### ISSUE TITLE
doesn't recognize monks enhanced journal type "image"

### ISSUE THREAD

**Issue by SwedishRabbit** [jagoe/fvtt-module-automated-combat-notes#16]
It will not open a correct look of the monks enhanced journal type picture.
First picture is how it looks when i open it normally.
Second picture is how it looks when the combat triggers it.
![1](https://github.com/jagoe/fvtt-module-automated-combat-notes/assets/128657928/e960b80e-fa68-4b67-94a3-5d4155178b3b)
![2](https://github.com/jagoe/fvtt-module-automated-combat-notes/assets/128657928/b7273d63-4075-4788-b2cf-387238e4a0e0)

**Comment by jagoe** [comment]
Thanks for the submission 👍 I'll take a look at it tomorrow.

**Comment by jagoe** [comment]
Thanks for the submission 👍 I'll take a look at it tomorrow.

**Comment by jagoe** [comment]
@SwedishRabbit I released a new version (v1.1.2) that should display MEJ entries correctly.

**Comment by SwedishRabbit** [comment]
> @SwedishRabbit I released a new version (v1.1.2) that should display MEJ entries correctly.

Wow i will test it! Thanks 🙂
