### ISSUE TITLE
Repeating URL Update Request in Foundry

### ISSUE THREAD

**Issue by Armandeus66** [jagoe/fvtt-module-automated-combat-notes#22]
Since the newest update of this module, I am asked every time I check for module updates if I want to update the link for this module. I click yes, and am asked again the next time.

**Comment by jagoe** [comment]
Thanks for bringing this up and sorry for the inconvenience. I'll try to take a look at it, but I'm pretty busy for the next two to three weeks, so I can't promise anything until after then.

**Comment by jagoe** [comment]
@Armandeus66 Sorry you had to wait. The issue should be resolved now and it shouldn't happen again in the future. I'll close the issue once you have confirmed the resolution or once a week has passed without feedback.

**Comment by Armandeus66** [comment]
Thank you!
